### ISSUE TITLE
更换数据源

### ISSUE THREAD

**Issue by mslxl** [sdufeACM/contestView#1]
JSON格式: https://contest.sdufeacm.club/data
RSS FEED:  https://contest.sdufeacm.club/atom.xml

目前数据是在每天的 0 点和 12 点更新

邮箱订阅等期末再写, 需要加一个订阅界面

**Comment by xia0ne** [comment]
您的订阅页面指有啥功能 @mslxl

**Comment by mslxl** [comment]
需要一个邮箱订阅的界面和一个日历订阅的界面

---

邮箱订阅需要以下内容
- 邮箱地址
- 订阅比赛源 source (即对 source 字段的过滤)
- 截止日期 day (在还剩 day 天的时候才发送邮件通知)
点击确定订阅按钮后应向指定的 URL 发送一个请求

---

日历订阅只需要两个字段
- 订阅比赛源 source (即对 source 字段的过滤)
- 截止日期 day (仅显示 day 天内的比赛)
选择后应生成一串 URL


不过上述内容目前还没有服务器实现, 要等假期再写

目前有关两个参数的作用可以参见:

- 仅显示 CF: https://contest.sdufeacm.club/data?source=Codeforces 或 https://contest.sdufeacm.club/atom.xml?source=Codeforces
- 仅 2 天内: https://contest.sdufeacm.club/data?day=2 或 https://contest.sdufeacm.club/atom.xml?day=2
- 如不指定 source 和 day, 默认显示 7 天中的数据库中的所有比赛

**Comment by xia0ne** [comment]
good
